/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.RefData;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-11-10T23:55:43.430Z")

@Api(value = "conditions", description = "the conditions API")
public interface ConditionsApi {

    @ApiOperation(value = "Get weather options", notes = "", response = RefData.class, responseContainer = "List", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = RefData.class, responseContainer = "List"),
        @ApiResponse(code = 500, message = "Server error", response = Void.class) })
    
    @RequestMapping(value = "/conditions",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<RefData>> getWeatherOptions();

}
