swagger: "3.0.0"
info:
  description: ""
  version: "1.0.0"
  title: "Weether API"
host: ""
basePath: ""

schemes:
- "http"

paths:
  /conditions:
    get:
      summary: "Get weather options"
      operationId: "getWeatherOptions"
      produces:
      - "application/json"
      responses:
        200:
          description: "Success"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/RefData"
        500:
          description: "Server error"

definitions:
  RefData:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "string"
      name:
        type: "string"
